version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: db_alura_livros
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_alura_livros_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

volumes:
  mongodb_alura_livros_data:
