services:
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - mongodb_network

  ubuntu-python:
    image: ubuntu:latest
    container_name: ubuntu-python
    command: tail -f /dev/null
    build: .
    networks:
      - mongodb_network

networks:
  mongodb_network:
    driver: bridge